{% set name = "zc.lockfile" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 307ad78227e48be260e64896ec8886edc7eae22d8ec53e4d528ab5537a83203b

build:
  preserve_egg_dir: True
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=2
    - pip
  run:
    - python >=2
    - setuptools

test:
  imports:
    - zc
    - zc.lockfile

about:
  home: https://github.com/zopefoundation/zc.lockfile
  license: ZPL-2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Basic inter-process locks'
  dev_url: https://github.com/zopefoundation/zc.lockfile

extra:
  recipe-maintainers:
    - carlodri
