{% set name = "zc.lockfile" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96cb13769e042988ea25d23d44cf09342ea0f887083d0f9736968f3617665853

build:
  preserve_egg_dir: True
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - zc
    - zc.lockfile

about:
  home: https://github.com/zopefoundation/zc.lockfile
  license: ZPL-2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Basic inter-process locks'
  dev_url: https://github.com/zopefoundation/zc.lockfile

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
