travis:
  secure:
    BINSTAR_TOKEN: V05AJwM8AHBR9xMkMEwKA0dEAtS7+zYk9+xIKr68nCvQTpy7VJKAZSmas0KbjyjyeEe7rm/YF/JHG6xEEmW1mFEx9xi/+dpx/Ar3iRPbuC1IlKB3xCcdmBQMP8kCzM8f+yZeWnx3+ZCVgorVO60WDgGf79s41JqOqwjO7c5qJhAtzlT+bi6fol8K84l6HiT+djxy2LaumosAOCK6RiCyTC4wxS6y2NWvH7FC+zAIVq8UQfQf4bmbm1wtxJetJCRlCr0T/V5P4Xd1A0p4enWb9s8aW/q1whSHCg6jrOPerubu58W4xQ2XktT6B858PyrH3FxJlq2r7Ot+BOMbpihlWYb/uMh+wR8xfDKJKOOjY3PTbfVvF84RWpINcEv7YcVpGG27BGB08YjXw9CRzN/MOw4CNVDkhBTtYX0qqjM8aXj6F469ahMOLiPRFCEkoZb+waBxXJGG0kxhd60CqfKCUMT7/sZ9BMT8frUCFn6njRqIjwpEIlOY861lx55GR69DOrmqmpMMWR3d6qE4IATcRbL5wSv0PJdgeaBYgpDV8sP91yyzgQtG4djEMSzOq06FqgKWlSkjx9n46HKxlroBBVom/vaqLRJrjGV6yWXTJC2LGCnx/5Np4mF34lKpw9il5E6K1hi1gUz1YQSgNq1NMgLTfg/S2rkkaw+FP0s5o8k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
